### ISSUE TITLE
Bug/question: Month view does not 

### ISSUE THREAD

**Issue by Gjessing1** [YukiGasai/obsidian-google-calendar#7]
Month view, clicking a date with no events gives the following text "No events found enter to create a new one", but pressing enter does not open the Create Google Calendar Event. Maybe a bug or I am misunderstanding something?

View I am using:
"gEvent
type: month
date: today
navigation: true
"

![image](https://user-images.githubusercontent.com/59605485/185372825-80c1a67e-eb9c-4ab0-9ee6-47c955309c38.png)

Thanks again for a great plugin, using it daily 😊

**Comment by YukiGasai** [comment]
I totally forgot about this function ^^. It should work now.
Thank you for testing.

**Comment by Gjessing1** [comment]
Thanks for quick reply, but could not see a new version, so i decided to reinstall the plugin but when trying to add it again trough BRAT i  get "This release is not complete and cannot be download. main.js missing....".

Did i get something wrong or has something on the rep changed?

**Comment by YukiGasai** [comment]
My bad. I created a new version for the last commit. 1.1.8 should work now.

**Comment by Gjessing1** [comment]
Working great now, thankd alot! Any way to contribute to the project? Do you have a buymeacoffe account?

**Comment by rednave12** [comment]
Checked I'm on the latest version but I'm still experiencing this issue, I can create events in other ways just fine but pressing enter doesn't do anything. Looked in the code, saw there was a handler for shift + enter, which correctly opens the event details view. TIA :)
