### ISSUE TITLE
Filter based on category

### ISSUE THREAD

**Issue by nickcalamaro** [YukiGasai/obsidian-google-calendar#93]
I'm trying to set up a schedule view that only shows events with a certain category (Google has names for these such as Tomato, Sage, Flamingo).

I'm wondering whether this is something I can do natively with custom YAML or whether this needs an enhancement on the app. Is that something that consider being added or is there a workaround that can do something similar (get a subset of events in a given time period).

**Comment by YukiGasai** [comment]
Hi @nickcalamaro,
nice to see yet another way of using the calendar :)
I really like your idea, so I implemented the filter on top of the already existing include exclude option.
Currently, the colors only work for event colors not calendar colors, that means only if you updated the color of the event.
I mapped the colors to the english names, if you find any error, just let me know.


Example of only showing Yellow (Banana) and Blue (Peacock) events:

~~~
```gEvent
date: 2023-03-28
type: schedule
include: ["Banana", "Peacock"]
```
~~~

The name of the color can be seen on hover inside the webapp.

---

For your work on the dataview, the `getEvents()` will return a array of Google Event Objects, you have to parse the data yourself. My first idea would be using map to iterate over all objects and create a new object with the data you want to keep or just a string with the summary

Example

~~~
```dataviewjs
const {getEvents} = this.app.plugins.plugins["google-calendar"].api

const events = await getEvents();
const highPrio = events.filter(d => d.colorId == 11).map(event => event.summary)

dv.list(highPrio);  
```
~~~

**Comment by nickcalamaro** [comment]
Thank you so much, what a speedy update and works great! 

And thanks for the pointers about working with the dataview. Still getting used to parsing data. It seems like string manipulation works okay in a pinch but that can get quite messy so much easier to have the filter in now.
